PTS1:
  dingwei_path : "../data/dingwei_feature.csv"
  budingwei_path : ../data/budingwei_feature.csv
  rest_path : ../data/rest_8k_feature.csv
  agent1_result : '../data/pts1/result/agent1_classification_top1000.csv'

  result_save_path : ../data/pts1/result/
  fig_save_path : ../data/pts1/fig_process/
  cv: False
  regression : False

  shuffle : False
  length : 1000

GB1:

  agent1_result : '../data/GB1/result/agent1_classification_top1000.csv'

  processed_data_path : '../data/GB1/dataset/processed/'
  result_save_path: '../data/GB1/result/'
  fig_save_path : '../data/GB1/fig_process/'

  cv : False
  regression : False

  shuffle : False
  length : 4000

PhoQ:

  agent1_result : '../data/PhoQ/result/agent1_classification_top1000.csv'

  processed_data_path : '../data/PhoQ/dataset/processed/'
  result_save_path: '../data/PhoQ/result/'
  fig_save_path : '../data/PhoQ/fig_process/'

  cv : False

  regression : False

  shuffle : False
  length : 13000


GB1_score3_consider1ps:
  agent1_result : '../data/GB1_score3_consider1ps/result/agent1_classification_top1000.csv'
  processed_data_path : '../data/GB1_score3_consider1ps/dataset/processed/'
  result_save_path: '../data/GB1_score3_consider1ps/result/'
  fig_save_path : '../data/GB1_score3_consider1ps/fig_process/'

  cv : False


  shuffle : False
  length : 4000

GB1_set1ps_change2ps_consider1ps:
  agent1_result : '../data/GB1_set1ps_change2ps_consider1ps/result/agent1_classification_top1000.csv'
  processed_data_path : '../data/GB1_set1ps_change2ps_consider1ps/dataset/processed/'
  result_save_path: '../data/GB1_set1ps_change2ps_consider1ps/result/'
  fig_save_path : '../data/GB1_set1ps_change2ps_consider1ps/fig_process/'

  cv : False


  shuffle : False
  length : 4000